# Generated by Django 4.0.1 on 2022-03-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_customuser_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isFilled',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
