# Generated by Django 4.0.1 on 2022-03-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_customuser_isfilled'),
    ]

    operations = [
        migrations.CreateModel(
            name='userPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre1', models.CharField(max_length=50)),
                ('genre2', models.CharField(max_length=50)),
                ('genre3', models.CharField(max_length=50)),
            ],
        ),
    ]
