# Generated by Django 4.0.1 on 2022-03-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreferences',
            name='userId',
            field=models.IntegerField(default=0),
        ),
    ]
