# Generated by Django 4.0.1 on 2022-01-17 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieId', models.AutoField(primary_key=True, serialize=False)),
                ('movieTitle', models.CharField(max_length=100)),
                ('movieDescription', models.CharField(max_length=1000)),
                ('movieKeywords', models.CharField(max_length=500)),
                ('movieCast', models.CharField(max_length=500)),
                ('movieDirector', models.CharField(max_length=100)),
                ('movieProduction', models.CharField(max_length=500)),
                ('movieRuntime', models.IntegerField()),
                ('movieGenre', models.CharField(max_length=150)),
                ('movieTagline', models.CharField(max_length=100)),
                ('movieRating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
