# Generated by Django 4.0.1 on 2022-01-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieOperations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieCast',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieDescription',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieDirector',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieGenre',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieKeywords',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieProduction',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movieTagline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
