# Generated by Django 4.0.1 on 2022-01-20 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieOperations', '0003_movie_movieurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='moviePoster',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
