# Generated by Django 4.0.1 on 2022-02-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieOperations', '0005_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieUrl',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
