# Generated by Django 4.0.1 on 2022-02-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieOperations', '0006_alter_movie_movieurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='likecount',
            field=models.IntegerField(default=0),
        ),
    ]
