# Generated by Django 4.0.1 on 2022-03-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieOperations', '0007_movie_likecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ratecount',
            field=models.IntegerField(default=0),
        ),
    ]
