# Generated by Django 4.0.1 on 2022-03-01 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieOperations', '0008_movie_ratecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movieRating',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
